version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - /etc/devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
  harbour:
    image: ${HARBOUR_IMAGE}
    expose:
      - "8080"
  port:
    image: ${PORT_IMAGE}
    expose:
      - "8082"
  stevedore:
    image: ${STEVEDORE_IMAGE}
    expose:
      - "8080"
  shipping:
    image: ${SHIPPING_IMAGE}
    expose:
      - "8080"
    volumes:
      - /etc/devops/config/shipping/URL_config.json:/home/data/URL_config.json

