version: "3.9"
services:
  harbour:
    image: ${HARBOUR_IMAGE}
    ports:
      - 8080:8080
  port:
    image: ${PORT_IMAGE}
    ports:
      - 8081:3000
  stevedore:
    image: ${STEVEDORE_IMAGE}
    ports:
      - 8082:80
  shipping:
    image: ${SHIPPING_IMAGE}
    ports:
      - 8083:80
