version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - /etc/devops/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  harbour:
    image: ${HARBOUR_IMAGE}
    ports:
      - 8080:8080
  port:
    image: ${PORT_IMAGE}
    ports:
      - 8081:8082
  stevedore:
    image: ${STEVEDORE_IMAGE}
    ports:
      - 8082:80
  shipping:
    image: ${SHIPPING_IMAGE}
    ports:
      - 8083:80

