
name: Test on Master Push
# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]

jobs:
    build-and-deploy:
      name: Setup, Build and Publish
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: "Verify Build"
        working-directory: ./experimental/user-project/user-example
        run: |
          mvn --batch-mode --update-snapshots test 
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
