name: Test release tag
# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
    build-and-deploy:
      name: Setup, Build and Publish
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Get Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build with Maven"
        working-directory: ./experimental/user-project/user-example
        run: |
          mvn --batch-mode --update-snapshots package -P packageAsDocker
          docker build ./docker -f ./docker/Dockerfile -t ghcr.io/${{ github.repository_owner }}/test:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/test:${{ env.RELEASE_VERSION }}
      - name: "Upload docker-compose yaml to VM"
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.AZURE_VM_USER }}'
          server: '${{ secrets.AZURE_VM_HOST }}'
          ssh_private_key: '${{ secrets.AZURE_VM_KEY }}'
          local_path: './experimental/user-project/user-example/docker/docker-compose.yml'
          remote_path: '/tmp/docker-compose.yml'
      - name: "Run Compose on Azure"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            USER_CONTAINER=ghcr.io/${{ github.repository_owner }}/test:${{ env.RELEASE_VERSION }} docker-compose -f /tmp/docker-compose.yml up -d
          
