name: Test release tag
on: repository_dispatch
    
jobs:
    build-and-deploy:
      name: Setup, Build and Publish
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Test'
        run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
