name: Update Deployment on Repository Dispatch
on: 
    repository_dispatch:
        types: [deploy]
        
env:
  PERMITTED_REPOS: '["HARBOUR_IMAGE", "SHIPPING_IMAGE", "PORT_IMAGE", "STEVEDORE_IMAGE"]'
    
jobs:
    pull-and-deploy:
      name: Pull and Deploy the latest image
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: "Checkout"
        uses: actions/checkout@v2.4.0
      - name: 'Update ENV vars'
        run: |
            echo "IMAGE_OWNER=${{ github.event.client_payload.image_owner }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
      - name: "Check payload is from permitted repo"
        if: ${{ !contains(env.PERMITTED_REPOS, env.IMAGE_OWNER) }}
        uses: actions/github-script@v5.0.0
        with:
            script: |
                core.setFailed('Image owner set incorrectly.')
      - name: Update Secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: ${{ env.IMAGE_OWNER }}
          value: ${{ env.IMAGE_TAG }}
          token: ${{ secrets.REPO_TOKEN }}
          org: true
      - name: "Upload docker-compose yaml to VM"
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.AZURE_VM_USER }}'
          server: '${{ secrets.AZURE_VM_HOST }}'
          ssh_private_key: '${{ secrets.AZURE_VM_KEY }}'
          local_path: './docker-compose/docker-compose.yml'
          remote_path: '/etc/devops/docker-compose/docker-compose.yml'
      #- name: "Update nginx.conf"
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.AZURE_VM_HOST }}
      #    username: ${{ secrets.AZURE_VM_USER }}
      #    key: ${{ secrets.AZURE_VM_KEY }}
      #    port: 22
      #    script: |
      #      cd /etc/devops/nginx-gen/
      #      python3 main.py --compose /etc/devops/docker-compose/docker-compose.yml --nginx /etc/devops/nginx/template-nginx.conf --out /etc/devops/nginx/nginx.conf --deny nginx
      - name: "Run Compose on Azure"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_KEY }}
          port: 22
          script: |            
            docker stop $(docker ps -a -q)
            HARBOUR_IMAGE=${{ secrets.HARBOUR_IMAGE }} \
            PORT_IMAGE=${{ secrets.PORT_IMAGE }} \
            SHIPPING_IMAGE=${{ secrets.SHIPPING_IMAGE }} \
            STEVEDORE_IMAGE=${{ secrets.STEVEDORE_IMAGE }} \
            docker-compose -f --remove-orphans /etc/devops/docker-compose/docker-compose.yml up -d


