name: Second Part of Deploying Latest Images
on: 
    repository_dispatch:
        types: [update]
        
    
jobs:
    deploy:
      name: Deploy the latest image
      runs-on: ubuntu-latest
      steps:
      - name: "Checkout"
        uses: actions/checkout@v2.4.0
      - name: "Upload docker-compose yaml to VM"
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.AZURE_VM_USER }}'
          server: '${{ secrets.AZURE_VM_HOST }}'
          ssh_private_key: '${{ secrets.AZURE_VM_KEY }}'
          local_path: './docker-compose/docker-compose.yml'
          remote_path: '/etc/devops/docker-compose/docker-compose.yml'
      #- name: "Update nginx.conf"
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.AZURE_VM_HOST }}
      #    username: ${{ secrets.AZURE_VM_USER }}
      #    key: ${{ secrets.AZURE_VM_KEY }}
      #    port: 22
      #    script: |
      #      cd /etc/devops/nginx-gen/
      #      python3 main.py --compose /etc/devops/docker-compose/docker-compose.yml --nginx /etc/devops/nginx/template-nginx.conf --out /etc/devops/nginx/nginx.conf --deny nginx
      - name: "Run Compose on Azure"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_KEY }}
          port: 22
          script: |            
            docker stop $(docker ps -a -q)
            HARBOUR_IMAGE=${{ secrets.HARBOUR_IMAGE }} PORT_IMAGE=${{ secrets.PORT_IMAGE }} SHIPPING_IMAGE=${{ secrets.SHIPPING_IMAGE }} STEVEDORE_IMAGE=${{ secrets.STEVEDORE_IMAGE }} docker-compose -f /etc/devops/docker-compose/docker-compose.yml up --remove-orphans -d



    
